# yaml-language-server: $schema=https://moonrepo.dev/schemas/tasks.json
implicitInputs:
  - 'package.json'
  
tasks:
    format:
        command:
            - 'dprint'
            - 'fmt'
            - '--config'
            - '@in(0)'
            # - '--verbose'
        inputs:
            - '/dprint.json'
            - '**/*'

    lint:
        command:
            - 'dprint'
            - 'check'
            - '--config'
            - '@in(0)'
            # - '--verbose'
        inputs:
            - '/dprint.json'
            - '**/*'

    typecheck:
        command:
            - 'tsc'
            - '--build'
            # - '--verbose'
        inputs:
            # Source and test files
            - 'src/**/*'
            - 'tests/**/*'
            # Type declarations
            - 'types/**/*'
            # Project configs
            - 'tsconfig.json'
            - 'tsconfig.*.json'
            # Root configs (extended from only)
            - '/tsconfig.options.json'
