name: Deploy Preview

on:
  pull_request:

jobs:
  neon:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
      - uses: neondatabase/create-branch-action@v3
        id: create_branch
        with:
          api_key: ${{ secrets.NEON_API_KEY }}
          project_id: ${{ vars.NEON_PROJECT_ID }}
          branch_name: ${{ github.event.pull_request.base.sha }}
          username: ${{ secrets.PG_USERNAME }}
          password: ${{ secrets.PG_PASSWORD }}
      - name: Comment on Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr comment 1 --body "Hi from GitHub CLI\nNeon branch :elephant: : https://console.neon.tech/app/projects/${{ vars.NEON_PROJECT_ID }}/branches/${{ steps.create_branch.outputs.branch_id }}"
