name: Deploy Preview

on:
  pull_request:

#     curl --request POST \
#      --url https://console.neon.tech/api/v2/projects/ancient-hat-488165/branches \
#      --header 'accept: application/json' \
#      --header 'authorization: Bearer 9cip0pyjy0m0egs5hzf4e3u2p33wovdzlwaqk086nxalu78l8bw55zictb9jj0sq' \
#      --header 'content-type: application/json' \
#      --data '
# {
#   "endpoints": [
#     {
#       "type": "read_write",
#       "autoscaling_limit_max_cu": 0.25,
#       "autoscaling_limit_min_cu": 0.25,
#       "suspend_timeout_seconds": 120
#     }
#   ],
#   "branch": {
#     "name": "test"
#   }
# }
# '

jobs:
  neon:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.2
      - name: Get PR sha
        env:
          TEST: ${{ github.event.pull_request.head.ref }}
        run: |
          echo $TEST
      # - uses: neondatabase/create-branch-action@v3
      #   id: create_branch
      #   with:
      #     api_key: ${{ secrets.NEON_API_KEY }}
      #     project_id: ${{ vars.NEON_PROJECT_ID }}
      #     branch_name: ${{ github.event.pull_request.base.sha }}
      #     username: ${{ secrets.PG_USERNAME }}
      #     password: ${{ secrets.PG_PASSWORD }}
      # - env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   run: |
      #     gh pr comment 1 --body "Hi from GitHub CLI\nNeon branch :elephant: : https://console.neon.tech/app/projects/${{ vars.NEON_PROJECT_ID }}/branches/${{ steps.create_branch.outputs.branch_id }}"
