on: [push]


jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - run: echo lint
  test: 
    runs-on: ubuntu-latest
    name: Test
    steps:
      - run: echo test
  build:
    runs-on: ubuntu-latest
    needs: [lint, test]
    name: Build
    steps:
      - run: echo build
  deploy:
    runs-on: ubuntu-latest
    needs: [lint, test, build]
    environment: test (Production)
    permissions:
      contents: read
      deployments: write
      pull-requests: write
    name: Deploy to Cloudflare Pages
    steps:
      - uses: actions/checkout@v3.5.0
      - uses: pnpm/action-setup@v2.2.4
      - uses: actions/setup-node@v3.6.0
        with:
          node-version-file: '.nvmrc'
          architecture: 'x64'
      - name: Build
        env:
          BUILDING: true
          VITE_TIME: ${{ vars.VITE_TIME}}
          PUBLIC_API_URL: ${{ vars.PUBLIC_API_URL }}
        run: pnpm install --frozen-lockfile && pnpm nx run-many -t build --skip-nx-cache
      - name: Publish
        id: publish
        uses: cloudflare/pages-action@v1.5.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ vars.CLOUDFLARE_ACCOUNT_ID }}
          projectName: ${{ vars.CLOUDFLARE_PROJECT_NAME }}
          directory: ${{ vars.ASSET_DIRECTORY}}
          workingDirectory: ${{ vars.WORKING_DIRECTORY }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          echo "ID: ${{ steps.publish.outputs.id }}"
          echo "URL: ${{ steps.publish.outputs.url }}"
          echo "Environment: ${{ steps.publish.outputs.environment }}"
          echo "Alias: ${{ steps.publish.outputs.alias }}"
# https://github.com/cloudflare/pages-action/issues/16#issuecomment-1398478711
