# name: TearDown Preview

# on:
#   pull_request:
#     types: [closed, reopened]

# jobs:
#   label_issue:
#     runs-on: ubuntu-latest
#     steps:
#       - env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#           PR_URL: ${{ github.event.pull_request.html_url }}
#         run: |
#           gh issue edit $PR_URL --add-label "triage"
